### ISSUE TITLE
Fix dropdown colors on sm-md devices

### ISSUE THREAD

**Issue by dieghernan** [ropensci-org/rotemplate#47]
When I navigate to https://docs.ropensci.org/rtweet/ on my smartphone, the color of the navbar dropdown links make difficult to see the text:

![image](https://user-images.githubusercontent.com/25656809/109583640-7c444f00-7b00-11eb-9200-ca6ab6d81f6b.png)

**Comment by dieghernan** [comment]
So I think this is the culprit (coming from navbar.less stylesheet - Bootstrap)
```css
@media (max-width: 767px){
  .navbar-default .navbar-nav .open .dropdown-menu>li>a {
      color: #777;
  }
}
```
